baseURL = 'https://kwangsing3.github.io/'
locale = 'zh-tw'
title = '勃勃生機，萬物競發'

# Novela settings
theme = "github.com/forestryio/hugo-theme-novela"

paginate = 6

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
  [markup.goldmark.renderer]
    unsafe = true

[params]
defaultHero = "/images/hero-11.jpg"


[taxonomies]
author = "authors"
tag = "tags"

[params.giscus]
enabled = true
repo = "kwangsing3/kwangsing3.github.io"
repoId = "R_kgDOSywZxg"
category = "General"
categoryId = "DIC_kwDOSywZxs4C-oQc"
mapping = "pathname"
strict = "0"
reactionsEnabled = "1"
emitMetadata = "0"
inputPosition = "bottom"
theme = "preferred_color_scheme"
lang = "zh-TW"
